-- Ejecutar en Supabase SQL Editor una sola vez para habilitar guardado histórico de reportes AVE.

create table if not exists public.reportes_ave (
    id bigint generated by default as identity primary key,
    nombre_reporte text not null,
    curso_consolidado text not null,
    fecha_inicio_analisis date,
    fecha_fin_analisis date,
    fecha_inicio_curso date,
    fecha_fin_curso date,
    aulas_canvas jsonb,
    usuario_generador text,
    fecha_generacion timestamptz default now()
);

create table if not exists public.resumen_reportes_ave (
    id bigint generated by default as identity primary key,
    reporte_id bigint references public.reportes_ave(id) on delete cascade,
    total_estudiantes integer,
    avance_esperado_promedio numeric,
    avance_real_promedio numeric,
    brecha_promedio numeric,
    riesgo_bajo integer,
    riesgo_medio integer,
    riesgo_alto integer,
    nunca_ingreso integer,
    ingreso_no_inicio integer,
    modulo_1 integer,
    avance_parcial integer,
    avance_insuficiente integer,
    actividades_pendientes integer,
    combinacion_factores integer,
    fecha_registro timestamptz default now()
);

create table if not exists public.reporte_estudiantes_ave (
    id bigint generated by default as identity primary key,
    reporte_id bigint references public.reportes_ave(id) on delete cascade,
    canvas_course_id bigint,
    curso_aula text,
    canvas_user_id bigint,
    nombre text,
    correo text,
    section_id bigint,
    estado_inscripcion text,
    ultimo_ingreso timestamptz,
    ultima_entrega timestamptz,
    ultima_actividad timestamptz,
    dias_sin_actividad integer,
    tiempo_total_min numeric,
    actividades_total integer,
    actividades_completadas integer,
    actividades_pendientes integer,
    avance_real_pct numeric,
    avance_esperado_pct numeric,
    brecha_pct numeric,
    modulo_maximo integer,
    modulo_maximo_nombre text,
    estado_base text,
    puntaje_riesgo integer,
    nivel_riesgo text,
    causa_principal_riesgo text,
    causas_riesgo text,
    recomendacion text,
    fecha_registro timestamptz default now()
);
